@startuml 

title Eisfeld - Class Diagram 

class SnowStorm { 
    +void tryStorm() 
} 


abstract class Item { 
    +void thrownDown() 
    +void pickedUp(Player Picker) 
    +void diggedUp() 
    +void used(Player p, Activity a) 
} 

class Food { 
    +void used(Player p, Activity a) <<override>> 
} 

class Rope { 
    +void used(Player p, Activity a) <<override>> 
} 

class Shovel { 
    +void used(Player p, Activity a) <<override>> 
} 

class DivingSuit { 
    +void used(Player p, Activity a) <<override>> 
} 

class FragileShovel{
    +void used(Player p, Activity a) <<override>>
}

class SignalFlarePart { 
    -int partID 
    +void used(Player p, Activity a) <<override>> 
} 



class Tent{
    +void used(Player p, Activity a) <<override>>
}

Item <|-- Tent
Item <|-- SignalFlarePart 
Item <|-left- Food 
Item <|-left- Rope 
Item <|-left- Shovel 
Item <|-left- DivingSuit 

Shovel <|-- FragileShovel

class SignalFlare { 
    +void putTogether(RoundController rc) 
} 

SignalFlarePart "3"--* SignalFlare 
SignalFlare ..> RoundController 
SignalFlare --> PositionLUT 

abstract class Tile { 
    #int x 
    #int y 
    #int snow 
    -boolean igluOn 
    +boolean tentOn
    +void steppedOn(Player p) 
    +void steppedOff(Direction dir) 
    +int changeSnow(signed int thisMuch) 
    +Tile getNeighbour(Direction dir)
    +void destroyIglu()
    +void buildIglu()
    +void putOnTent()
    +boolean equals(Tile tile)
    +boolean getIgluOn()
    +
} 

class StableTile 
class UnstableTile { 
    -int capacity 
    +int standingHere 
} 

class SnowyHole

Tile <|-- StableTile 
Tile <|-- UnstableTile 
Tile <|-- SnowyHole 

enum Direction { 
    up 
    down 
    left 
    right 
    here
    
    +Direction valueOf(int direction)
    +int valueOf(Direction dir)
    +getValue()
} 

enum ItemState { 
    frozen 
    inHand 
    thrownDown 
} 

Item -down-> ItemState 
Tile --> Direction 

class PositionLUT << (S,#FF7700) Singleton >> { 
    +Tile getPosition(Player p) 
    +Tile getPosition(Item i) 
    +Player[] getPlayersOnTile(Tile t) 
    +Item[] getItemsOnTile(Tile t) 
    +Tile getTile(int x, int y) 
    +void setPosition(Player p) 
    +void setPosition(Item i) 
    +void setPosition(PolarBear pb)
    +Tile getPosition(PolarBear pb)
} 

PositionLUT "tileList\n36" *-- Tile 
PositionLUT "itemTileMap\t\n0..7\t\t" o-- Item 
PositionLUT "tileItemMap\n0..7" o-- Item 

class RoundController { 
    -int curID 
    +void init(int playerNum) 
    +void startNextRound() 
    +void endLastRound()
    +void lose(String cause) 
    +void win() 
    +PlayerContainer getPlayerContainer() 
    +void checkTent()
} 

RoundController --> "ss"SnowStorm 
RoundController --> "it"Item 
RoundController --> "t"Tile 
RoundController --> "sg"SignalFlare
RoundController --> "tent"Tent
Player "roundController"--> RoundController 
SnowStorm --> PositionLUT 

@enduml
